services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    container_name: the-api
    networks:
      - app
    volumes:
      - .:/app
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - ${PORT:-3000}:${PORT:-3000}
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - '6379:6379'

networks:
  app:
    driver: bridge

volumes:
  postgres:
