services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    container_name: outvio-api
    depends_on:
      - postgres
    networks:
      - app
    volumes:
      - .:/app
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - ${PORT:-3000}:${PORT:-3000}
networks:
  app:
    driver: bridge

volumes:
  postgres:
